services:
  alexa2mstodo:
    image: ghcr.io/tompsg-git/alexa2mstodo:latest
    # build: .
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Berlin
      - CONFIG_PATH=/config/config.json
      - LOG_LEVEL=INFO
    restart: unless-stopped
